version: "3"

services:
  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    volumes:
       - ./blackbox-exporter/config.yml:/etc/blackbox_exporter/config.yml

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    ports:
      - 9090:9090
    depends_on:
      - blackbox-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana

  test:
    build: test
    profiles:
      - testing
    depends_on:
      - grafana