name: Test
on:
  push:
  schedule:
    - cron:  '45 14 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        run: docker-compose --profile testing up --abort-on-container-exit --exit-code-from test test
      - name: Cleanup 
        run: docker-compose down --volumes
